#
# Insight Timer HLS transcoding via ffmpeg
#

# HLS (m3u8) -> FLAC (lossless transcode for squeezelite/WiiM)
m3u8 flc * *
	# R:{PATH=%F}T:{START=-ss %t}E:{NOSTART=I}
	[ffmpeg] -v 0 -vn $START$ -protocol_whitelist file,http,https,tcp,tls -i $URL$ -acodec copy -f flac -
